version: 2.1

orbs:
  node: circleci/node@5.1.0
  docker: circleci/docker@2.2.0

jobs:
  build_and_test:
    working_directory: ~/project
    parallelism: 1
    executor: node/default
    steps:
      - checkout:
          path: ~/project
          persist_to_workspace: true
          fetch_depth: 1

      - node/test:
            pkg-manager: npm 
            resource_class: large 
            test-results-for: jest 
            app-dir: ~/project/client 

      - node/test:
            pkg-manager: npm 
            resource_class: large 
            test-results-for: jest 
            app-dir: ~/project/server 

      - docker/build:
          context: ./client
          dockerfile: Dockerfile
          tag: rakeshpotnuru/productivity-app:client

      - docker/build:
          context: ./server
          dockerfile: Dockerfile
          tag: rakeshpotnuru/productivity-app:server

      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - docker/push:
          context: ./client
          image: rakeshpotnuru/productivity-app:client

      - docker/push:
          context: ./server
          image: rakeshpotnuru/productivity-app:server

workflows:
  build_and_test:
    jobs:
      - build_and_test
